### ISSUE TITLE
live monitoring sa19 file instead of manual uploading...

### ISSUE THREAD

**Issue by AkhilJalagam** [sargraph/sargraph.github.io#1]
is it possible to use live monitoring the sar logs file instead of copying and uploading manually..?...
grafana is good but its needs a database.

**Comment by iamsureshraju** [comment]
If we need to use live monitoring, then we need a data source (like prometheus). The SAR graphs mostly used for offline views or at-least 1 minute refresh rate. We can use simple socket program to fetch the SAR date every 1 minute. I will try to work on it in future.

**Comment by iamsureshraju** [comment]
This tool is not targeted for live monitoring. Also we may have to install third party plugins or packages to achieve that. So I am skipping that development for now. Anyhow thank you for the suggestion.
