### ISSUE TITLE
Some reports does not work with older sysstat version

### ISSUE THREAD

**Issue by Shadok** [sargraph/sargraph.github.io#2]
Hello,

sar reports from a rhel 5 (sysstat-7.0.2-11.el5) have some differences and we don't have some report on your nice interface like CPU per example.

Here's a report.
[sa04_server.txt](https://github.com/sargraph/sargraph.github.io/files/3361530/sa04_server.txt)

Regards,

Shadok

**Comment by Shadok** [comment]
Too bad we don't have a graph with iowait from the cpu data (regardless sysstat version)

**Comment by iamsureshraju** [comment]
I have fixed the CPU page for RHEL5 and added the iowait chart to the page. Thanks for the valuable feedback.

**Comment by Shadok** [comment]
Thanks :)
