### ISSUE TITLE
ReferenceError: proc is not defined and Solaris sysstat

### ISSUE THREAD

**Issue by Shadok** [sargraph/sargraph.github.io#3]
Hello again,

I got this error with Solaris sa files : ReferenceError: proc is not defined
https://sarchart.dotsuresh.com/custom/sarchart-v4.3.min.js:1:1980

I wanted to test sar files from Solaris 5.8 and 5.10n since you don't list it as a compatible OS.
Here's 2 files.
[sa17_server_sol5.8.txt](https://github.com/sargraph/sargraph.github.io/files/3406454/sa17_server_sol5.8.txt)
[sa17_server_sol5.10.txt](https://github.com/sargraph/sargraph.github.io/files/3406455/sa17_server_sol5.10.txt)

Unrelated question, may i host your solution on an internal server ? I would like to make it able to fetch itself sar files when given the server (our servers don't have access to the net).
Code and copyright would be left unchanged, except for adding a box to put the targetted server name and fetching sar from it.

**Comment by iamsureshraju** [comment]
I am planning to include other OS. As of now only Linux and AIX are compatible. Solaris will be added by the end of this year.
If you are downloading for personal use, please feel free to use it with the copyright credits.
But if you are using it inside an organization, then please reach out to my email iamsureshraju@gmail.com.

**Comment by Shadok** [comment]
I don't know if you are aware of it but https://sarchart.weebly.com use your website.

**Comment by iamsureshraju** [comment]
Yes I am the moderator of that page. It was created long back. We have some regular followers on that site and so I left it open.

**Comment by iamsureshraju** [comment]
This repository is made as opensource and ready to download for offline usage. I have included Solaris OS as well. Kindly check
