### ISSUE TITLE
exporting to pdf is blank

### ISSUE THREAD

**Issue by ovitus** [sargraph/sargraph.github.io#4]
Exporting the sar graphs to a PDF file shows just blank templates, no graphs. See the attached document.
[chart.pdf](https://github.com/sargraph/sargraph.github.io/files/3570069/chart.pdf)

**Comment by iamsureshraju** [comment]
Hi Ovitus, Could you please share the file on what you uploaded. I will work on it and fix it if needed.

**Comment by iamsureshraju** [comment]
Now the online version of the tool is upgraded with lot more features. Hopefully your issue would have been fixed. Kindly use the site https://sarchart.dotsuresh.com. Kindly reopen the issue if not fixed.
