### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by oyearunpal** [sargraph/sargraph.github.io#5]
Hi, How I can run this locally. So that after doing changes and testing I can do git push.

**Comment by Shadok** [comment]
You can't if I'm not mistaken.

**Comment by oyearunpal** [comment]
Well If that is the case then I would say the developer has done some really good work on this project. I hope he will make it open source so that others can also contribute.

**Comment by Shadok** [comment]
I made sarcharts if you need something to install locally (and if i am not mistaken about this project).

**Comment by iamsureshraju** [comment]
Hi @oyearunpal , we can run this locally. Actually no data is sent to any server, everything runs in the client browser. Please try contact us option in https://sarchart.weebly.com to reach out to my email directly.

**Comment by iamsureshraju** [comment]
Hi @Shadok , I saw your github site. Its nice. Thank you adding my website credits on your page.

**Comment by Shadok** [comment]
@iamsureshraju You're welcome, it was only natural since your website inspired me.

**Comment by iamsureshraju** [comment]
Now the repository is made opensource and you can contribute.
