### ISSUE TITLE
How to export all graphs at once

### ISSUE THREAD

**Issue by fbezdeka** [sargraph/sargraph.github.io#6]
Hi!

Maybe I missed something, but when using the "Export Report" -> Save button the generated PDF contains the CPU graphs only.
How to export all graphs at once?

**Comment by iamsureshraju** [comment]
The current version provides only 3 charts to download. The new version is coming up (end of July) with more cool features and more charts to download as PDF.

**Comment by iamsureshraju** [comment]
Now the online version of the tool is upgraded with lot more features. Now the online tool allows to save all the graphs at once. Kindly use the site https://sarchart.dotsuresh.com
