### ISSUE TITLE
Normalize Y axe in memory section.

### ISSUE THREAD

**Issue by franrebo84** [sargraph/sargraph.github.io#8]
Hi! Thanks a lot for this project. Is useful as hell and looks amazing.

It would be great if the Y axe in memory section were in Mb or Gb instead of k or millions.  I tried to find this in the code but my node skill are awful.

BTW, I made a very simple Dockerfile to create a docker image. Ill PR as soon as posible.
Thanks!!

**Comment by iamsureshraju** [comment]
@franrebo84 I will try to implement the human readable format on Memory in the next version. Thank you for the feedback.

**Comment by iamsureshraju** [comment]
This is fixed in the online version. Kindly use the website https://sarchart.dotsuresh.com
