### ISSUE TITLE
No memory graphs created

### ISSUE THREAD

**Issue by fbezdeka** [sargraph/sargraph.github.io#9]
The following was created on a Debian system with the sysstat cronjob enabled (and tuned to do its job every minute) and afterwards converted into the .txt file using the command in the Readme of this repo.

When uploading this file the memory bars stay empty.

There is a javascript error, maybe this is the root cause.

```
sarchart-v4.32.min.js:1 Uncaught TypeError: Cannot read property 'clientWidth' of null
    at v (sarchart-v4.32.min.js:1)
    at HTMLAnchorElement.<anonymous> (sarchart-v4.32.min.js:1)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.y.handle (jquery.min.js:2)
```

Testfile: 
[report.txt](https://github.com/sargraph/sargraph.github.io/files/5355570/report.txt)

**Comment by iamsureshraju** [comment]
The website version is bit older which uses sarchart-v4.32.js. I am working on version 5 which will be updated soon. You can use the offline version in this github portal which will fix your issue.

**Comment by fbezdeka** [comment]
Thanks for the quick response!

The graphs are generated by the offline version as expected, but the export feature is missing. Is there a technical reason for that?

**Comment by iamsureshraju** [comment]
Yes, technically the offline version is made for local use where companies does not want to expose their data to outside world. The extract data will need to reach the highcharts server to plot the graph, so I have excluded that option from the offline version.

Anyhow the enhanced report version is coming up by the end of the month to the https://sarchart.dotsuresh.com website.
